### ISSUE TITLE
Add temples and other big structures to cities

### ISSUE THREAD

**Issue by jmespadero** [jmespadero/cityGen#1]
Write code to place singular objects as cathedrals or other temples.

A sample of a temple is on file [cityGen/cg-temple.blend](https://github.com/jmespadero/cityGen/blob/master/cg-temple.blend)

**Comment by jmespadero** [comment]
We start with a problem: Now, the regions are too random, so it is not easy to fit a temple in a region. Main problem is that regions are too big for a single building. 
Current model of the temple has a rectangular base of 20 x 28 meters approx.
![templescr](https://user-images.githubusercontent.com/6451497/32489692-0787980c-c3b1-11e7-8773-100a5d399b63.jpg)

The idea is to insert a "not random" set of seeds in cityGen2D.py to generate a region specially crafted to host a temple.
For example, here is a screenshot of a [voronoi  generator](http://alexbeutel.com/webgl/voronoi.html) which use 5 seeds to generate a quasi-rectangular central region:
![screenshot at 2017-11-07 11 53 55](https://user-images.githubusercontent.com/6451497/32490277-ddf46ba8-c3b2-11e7-9083-7e4cda1d3310.png)

We can later add a set of random seeds to create city regions, far enough to not break the original central region
![screenshot at 2017-11-07 11 58 16](https://user-images.githubusercontent.com/6451497/32490411-6b424df4-c3b3-11e7-96d0-0caacb76eda0.png)

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

first I'm trying to locate the temple in one random region, in a vertex. I'm trying to import the church model in the execution, but I'm thinking about the best way:
Best to load the model in execution time, including it in the cg-config.json file? or appending it permanently in the cg-libraryLite.blend and cg-library.blend?

What's more, the temple is composed by several model gropus (the walls, the stairs, the doors,...)... How can I group all of them in a single group, with object "temple" as father?

![captura de pantalla de 2017-11-07 19-31-55](https://user-images.githubusercontent.com/22729865/32510881-5da2223e-c3f2-11e7-9fd1-42c747f1ec1b.png)


Thanks in advance!

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

first I'm trying to locate the temple in one random region, in a vertex. I'm trying to import the church model in the execution, but I'm thinking about the best way:
 - Best to load the model in execution time, including it in the cg-config.json file? or appending it permanently in the cg-libraryLite.blend and cg-library.blend?

What's more, the temple is composed by several model gropus (the walls, the stairs, the doors,...)... How can I group all of them in a single group, with object "temple" as father?

![captura de pantalla de 2017-11-07 19-33-33](https://user-images.githubusercontent.com/22729865/32510923-908877e8-c3f2-11e7-8474-127f1559bf87.png)


Thanks in advance!

**Comment by jmespadero** [comment]
Hi,

Execute  `git pull upstream master` and you will get an update of the temple with a group named `Temple`.

**Comment by jmespadero** [comment]
And I have pushed a new branch named `templeRegion` with a hack to generate a region to host the temple.
if you move to the branch `templeRegion`, and execute `./run-cityGen2D.sh` you will get maps where the region 0 is always of the size of the temple. Like this:
![city map verbose](https://user-images.githubusercontent.com/6451497/32512942-e169ca94-c3f8-11e7-9315-6ce634d661c1.png)

If you see, the region 0 has the shape for the temple....
![screenshot at 2017-11-07 20 28 06](https://user-images.githubusercontent.com/6451497/32513372-529f96ac-c3fa-11e7-803c-dbf39109bf68.png)
![screenshot at 2017-11-07 20 27 56](https://user-images.githubusercontent.com/6451497/32513380-56b77282-c3fa-11e7-959f-da82d03d6ae5.png)

Please, don't touch cityGen2D.py. Keep working in cityGen3D.py

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've been working in the random location of the temple in a normal city. Now, I want to place the temple in the new city with the special region. I'm trying to do checkout to the templeRegion branch but I have some questions.

Mi local repository is synchronized with origin/master, and I want to have the branch upstream/templeRegion too, to finally access it as origin/templeRegion.

How can I get your branch? Because doing checkout is not enough as I had see.

Thanks in advance.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

It doesn't matter. I found the solution:
`git fetch upstream`
`git checkout -b templeRegion upstream/templeRegion`
`git pull origin templeRegion`
`git push -u origin templeRegion`

It works fine for me. Now I'm working in the templeRegion branch copied to my fork.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I think that I have the algorithm to locate the temple with a good orientation in the "temple region", after deleting the houses placed there.
Now I'm trying to create the temple in the scene, but I have the same problem than a week ago: the "Temple" is a point in the space and is not composed by several objects groups.

I think that I've pull your "templeRegion" changes well, because my new cities have a central region as you said, but the temple keeps being a simple point when I append it to the cg-librariLite.blend file.

What's more, does exist a way for including the Temple object in bpy, not appending it to the cg-libraryLite.blend file? Because I get this error:

![captura de pantalla de 2017-11-13 21-13-11](https://user-images.githubusercontent.com/22729865/32746933-7bc1dfba-c8b7-11e7-98fe-efba85972101.png)

With the DryLeaf object I hadn't errors, because DryLeaf is inside cg-libraryLite.blend file, but Temple object is not inside it.

Thanks in advance!

**Comment by jmespadero** [comment]
You have the method ```importLibrary(filename, link=False, destinationLayer=1, importScripts=True)``` in  `cityGen3D.py`,

Why don't you try to import the temple directly in the layer 0, and then translate/rotate the `Temple` object?
Hint: The seeds[0] + (0, 9.6) is a good location for the temple. You need no rotation by now.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

thanks, now I have the temple complete on the scene. I'm working in the correct location for it.

**Comment by jmespadero** [comment]
Then, do a push to your origin templeRegion branch so every one can enjoy it.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I'm pushing new content to my origin templeRegion branch and I have a problem:
When I import the "cg-temple.blend" library, I import the Temple in the destination layer 1 like the other objects (houses, walls, curbs...), because layer 0 is the game scene:
```
importLibrary(args['inputTemple'], link=False, destinationLayer=1, importScripts=True)
```

but then, when I try to create in layer 0 a copy of the temple:
```
temple = duplicateObject(bpy.data.objects["Temple"], "_temple")
temple.location = vector
```
it doesn't work properly and no temple object is shown into the scene.

Any idea of the problem?

What's more, I have successfully emptied the central region of houses, curbs and fences, as you can see (I have decided to also eliminate the curbs in that region):
![captura de pantalla de 2017-11-20 19-26-55](https://user-images.githubusercontent.com/22729865/33034652-ccc923f2-ce28-11e7-8a7b-0b0e63dc6849.png)


Thanks in advance.

**Comment by jmespadero** [comment]
We import objects from cg-library.blend into layer 1 because they are assets, we want to duplicate then after that.
But if we accept that there is only one temple per city, we can import it directly to layer 0 (as we do with the player, and the skyDome)

So I would use:
```python
    #Import the temple
    if args.get('inputTemple', False):
        importLibrary(args['inputTemple'], destinationLayer=0, importScripts=True)
        temple = bpy.data.objects['Temple']
        temple.location.xy = internalSeeds[0] + Vector((0, 9.6))
```

**Comment by jmespadero** [comment]
I would try not to empty the houses in region 0, but 'avoid' add houses there instead.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

Thanks for the temple code suggestions!
That is what I exactly have done, avoid add houses, not emptying the region after they're created.

I will comment any progress,
Thanks in advance.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

added new changes and pushing content to my repository fork. Thats the new Scene I have:
![captura de pantalla de 2017-11-26 19-02-33](https://user-images.githubusercontent.com/22729865/33242930-8063ea8e-d2dc-11e7-8c8d-b20cc7f218aa.png)

Thanks for your help

**Comment by sergiofv93** [comment]
Hello,

with the help of @jmespadero, I've already managed to create a region with the measures of the temple (for now at the coordinates (0.0, 0.0)) and the temple inside.

The next step will be to create a region with a predefined measurements, in which I will place a small market.

Following the same process, I will modify the cityGen2D.py file to define the relative coordinates for that region, which will be random located into the city. When I have created the region, I will place the market inside. In principle, the region must have a convex pentagonal shape.

By the way @jmespadero, I think will be useful to create a marketRegion branch at the upstream repository.

**Comment by jmespadero** [comment]
Hi, 
No need for a new branch, you can still work in the templeRegion branch, and we will merge to master when finished.

**Comment by sergiofv93** [comment]
Hi,

I have pushed new content to my fork repository. The news are a special region for a market location, emptied from houses and curbs, that has a pentagonal shape to locate the market.

So now, we have two specific regions in the map (not random). To create the market region, I have create a json file with its relative coordinates. Then, the algorithm generates a random seed and calculate the static coordinates for the other five seeds to generate the pentagonal region.

The market region, as the temple region, is emptied from houses and curbs. Here I paste an image of the scene:
![captura de pantalla de 2017-12-13 12-58-00](https://user-images.githubusercontent.com/22729865/33938304-56be5394-e007-11e7-87bc-947f9d349fa7.png)

Now, I have to create a market distribution and place it into the market region, and the issue will be finished successfully.

**Comment by jmespadero** [comment]
Look's nice. Next step is to generate a cg-Market.blend file with a set of objects that fills the region 0 in the above image.

**Comment by jmespadero** [comment]
Like this...
![cg-market](https://user-images.githubusercontent.com/6451497/33956650-81e7d652-e03f-11e7-8428-61458a7889df.jpg)

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I have upgrade the static buildings location algorithm. Now, we can locate any kind of building that we want giving the corresponding .blend file and adding it to the args when we execute cityGen2D.sh

The results for now are like you can see in the attached scene:
![captura de pantalla de 2017-12-27 21-05-45](https://user-images.githubusercontent.com/22729865/34392055-21dd341c-eb4a-11e7-8d21-a2976c76dc10.png)

I think that we have enough content to close this Issue2. Obviously, we could make the algorithm better, but I think it should be done in a future issue.

Waiting for your OK.

Greetings!

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I detected a bug in the algorithm pushed yesterday by me, it's about the empty of regions. When I execute cityGen3D with more than 2 static regions for buildings, the regions added was not emptied propperly of curbs.

Now it's solved. Waiting your OK!

Greetings!

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've not pushed content from a month. Changes we made at this point are useful for fixing several bugs about the location and shape of static regions (with the buildings). The problem was that static regions were locating at random positions and those positions could be between already placed seeds, greatly deforming the static region shape.

Here we have the regions **r5**(for a Market) and **r11**(for a Temple) with this bug:

![locationbug](https://user-images.githubusercontent.com/22729865/35416158-7ad72790-0228-11e8-87ae-9c7de6c4e7d1.png)



However, if we calculate some kind of radius for each static region, we could force new seeds to locate out of the radius circumference and fix this problem.

Greetings!

**Comment by jmespadero** [comment]
Please, delete all test.00* files from the repo. Those files are not considered sources, but test.

**Comment by jmespadero** [comment]
Hi @sergiofv93 ,

I have found the bug in your current  `buildStaticSeeds` function

The problem is that expression at line 288:
```python
[np.linalg.norm(r[0] - displacement) - r[2] for r in static_regions.values()]
```
 is not working because r[0] does not contain the coordinates of the central seed of the static_region, but its numerical id.

So, as a quick fix we can store the coordinates of central seed (or displacement) at line 308:
```python
    static_regions[i] = [fixedSeeds, name, radius, displacement]
```
and change the line 288 to be:
```python
while (min([np.linalg.norm(r[3] - displacement) - r[2] for r in static_regions.values()]) < radius):
    displacement = (1.5 * city_radius * np.random.random(2) - city_radius / 2)
```

This solution gave me another problem... the displacement is an numpy.array, which cannot be dumped to json. The easy thing is to convert it to a list at the end of the function with:
```python
    #Remove arrays from static region
    for id in static_regions:
        static_regions[id][3] = static_regions[id][3].tolist()
```


So, after some extra cleanup, my function now looks like this:
```python
def buildStaticSeeds(names, city_radius):
    print("Creating requested fix regions:", names)
    regionDict = {}
    fixedSeeds=0
    static_regions = {}

    for i, name in enumerate(names):
        reg_id = "f%d_%s"%(i, name)

        # Load relative seeds from "cg-XXXXXXX.json" file
        with open("cg-" + name + ".json", 'r') as f:
            aux_list = [[0, 0]] + json.load(f)
            radius = 5 + max([np.linalg.norm(x) for x in aux_list])
            # print("Read file cg-" + name + ".json", " -> radius",radius)

            if (i == 0):
                pos = np.asarray([0.0, 0.0])
            else:
                #print("previous fixed regions", [r[3] for r in static_regions.values()])

                pos = (1.5 * city_radius * np.random.random(2) - city_radius / 2).round(2)
                # Compute signed distances from point pos to each region
                # r[3] is position of fixedRegion. r[2] is radius of fixedRegion
                while (min([np.linalg.norm(r[3] - pos) - r[2] for r in static_regions.values()]) < radius):
                    #print("Invalid pos. Repeat...")
                    pos = (1.5 * city_radius * np.random.random(2) - city_radius / 2).round(2)

            # Displace seeds of this region 
            for x in aux_list:
                x[0] = x[0] + pos[0]
                x[1] = x[1] + pos[1]
            
            # Add pair <name, list> to the static seeds dictionary
            regionDict[reg_id] = aux_list

            #Debug info
            print(" * Build", name, "as", reg_id, "in region", fixedSeeds, "pos", pos)
            static_regions[i] = [fixedSeeds, name, radius, pos]
            fixedSeeds += len(aux_list)

    #Convert numpy arrays to lists
    for id in static_regions:
        static_regions[id][3] = static_regions[id][3].tolist()
        
    return regionDict, static_regions, fixedSeeds
```

What does it look to you?

Still not perfect.... after this precess, there are still problems with non-fixed seed in some cases.

**Comment by sergiofv93** [comment]
I think that works fine. Have you pushed it?

**Comment by jmespadero** [comment]
I can't commint to your repository, so I can't push.

If I push to my repository, and ask you to do a "git pull upstream", you probably will run into merge conflicts.

So, basically... copy & paste in your code.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I have fix the last bugs in this part of the code with the code you gave me and I have pushed what are supposed to be the final content to add to the templeRegion branch.
I think with these changes we could close the Issue#2, so I'll do a pull request to the parent repository.

Please, check these changes and give me your OK if all right.

Thanks in advance,
greetings.

**Comment by sergiofv93** [comment]
Hi @jmespadero 

I have added the last code fixes you request me and removed the river related files from the templeRegion branch.

I hope it will be right.

Thanks in advance,
greetings.

**Comment by jmespadero** [comment]
Accepted the merge-request #15

**Comment by jmespadero** [comment]
Accepted the merge-request #15
