### ISSUE TITLE
Problem with Blender 2.79

### ISSUE THREAD

**Issue by sergiofv93** [jmespadero/cityGen#12]
In Blender v2.79, import "numpy" doesn't work properly.

**Comment by jmespadero** [comment]
numpy is installed in the python interpreter bundled with blender in Windows, but not for linux.

If you get an error after executing `python3 -c "import numpy"`, then you should install numpy in the system python with one of this alternatives:

- sudo apt-get install python3-numpy 
- pip3 install numpy

**Comment by jmespadero** [comment]
@sergiofv93 Can you tell us if that solved your problem?

By the way... I have seen that numpy is only used in two lines, to compute the max distance of any vertex to the origin.
```groundRadius = 50+(np.linalg.norm(vertices, axis=1)).max()```

I suppose it is better to compute groundRadius  using [mathutils.Vector](https://docs.blender.org/api/current/mathutils.html#mathutils.Vector)  and drop the 
dependency of numpy in cityGen3D.py (You still will need numpy for cityGen2D.py)

```groundRadius = 50 + max([ Vector(v).length for v in vertices])```

Done as commit f33ecd9f7bb7606

**Comment by sergiofv93** [comment]
Problem solved!

Closing issue.
