### ISSUE TITLE
Bats overflying the streets.

### ISSUE THREAD

**Issue by sergiofv93** [jmespadero/cityGen#19]
This issue is for create a specific number of bats which have to be overflying the streets of the city.

All we need to do it is:
**1º.- the bat model, as a blender file.**
**2º.- design a new algorithm to insert the bats into the scene.**
**3º.- the algorithm will have a behaviour based on RMDF algorithm.**

Progress will be posted in this issue.

**Comment by sergiofv93** [comment]
Here we have the bat model to be used. For now, it has no kind of animation designed. It will be designed in future issues, although to model objects or characters is not the objective of the present proyect.

**Bat model:**
![bat](https://user-images.githubusercontent.com/22729865/45698219-cd963900-bb67-11e8-9e42-021b453d2a48.PNG)

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I'm trying to run my new algorithm over Windows 10, but I get the error **Cannot read 'city.data.json': no such file or directory**

However, I've run the next commands in blender shell, and you can see that "city.data.json" is correctly opened to extract information as the vertices or the internal regions, but the instruction "bpy.data.texts.load(file)" doesn't detect the file:

![error](https://user-images.githubusercontent.com/22729865/46178440-2b88f600-c2b7-11e8-8500-6172f7d955c0.JPG)

What's going on? I mean, the file already exists in the directory, the "open" line works propperly but the "load" line fails.

Have any solution for the problem?
Kind regards

**Comment by jmespadero** [comment]
Hi,

I don't have a windows10 machine, so I can't try that. It seems a bug that should be reported to blender3D, or at least be asked in their forum.

But, if you can read the file from python, you can try to write a workaround...

Instead of the call
```python
D.texts.load("city.data.json", True)
```

You can manually create a new Text object and set its value using `from_string()`
```python
#Create a text object and store the content of file 'city.data.json'
with open('city.data.json', 'r') as file:
    D.texts.new("city.data.json")
    D.texts["city.data.json"].from_string(file.read())
```

Please, tell us if it worked under windows10.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

that worked fine! But now I have the same problem with the line:

`with bpy.data.libraries.load(fileName, link=link) as (data_from, data_to):`


I get the next error:

![error](https://user-images.githubusercontent.com/22729865/46206438-42b1fd00-c324-11e8-94fc-8d92aec0ba29.JPG)

I think it's the same problem, but now I can't create a new "cg-libraryLite.blend" file, cause it's not empty and I need its content. As you can see, one of the error messages is the "no such file or directory" too.

Have any solution for the problem?
Kind regards

**Comment by jmespadero** [comment]
The error message states that you are trying to read `C:\cg-libraryLite.blend`. 
That is not correct.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

It works fine! I've run the script over Windows 10 and it works properly.

I've solved the error with the "C:\cg-libraryLite.blend" file giving the absolute path to the method, and now I'm searching for a code which allows me to give only a relative path.

Thanks for all,
Kind regards.

**Comment by jmespadero** [comment]
I suppose that the problem is that blender in windows does not set correctly the Current Work Directory (CWD) to the same directory of the scene file. 

https://blenderartists.org/t/is-current-working-directory-set-to-location-of-opened-blend/623171/3

Here is a proposed solution:
https://blenderartists.org/t/getting-current-working-directory-cwd-using-python-on-mac/456549/5

**Comment by sergiofv93** [comment]
Thanks, but I've found a code that works fine:

`bpy.data.libraries.load(os.getcwd() + "\\" + filename, link=link)`

Kind regards.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

We have new changes pushed to the repository:
1º.- 'Vampire' character has been added to the 'cg-monster.blend' file
2º.- 'Vampire' character now has some logic
3º.- I've added a basic algorithm to locate the vampires in the scene, and works properly
4º.- I've added another basic algorithm for vampires to move along the streets.

Here you have a screen capture of a flying vampire:
![captur](https://user-images.githubusercontent.com/22729865/46230360-ab22cd80-c368-11e8-9198-e3553631b4db.png)

The movement algorithm has to be fixed, because the vampire behaviour doesn't work fine for now.

Kind regards.

**Comment by jmespadero** [comment]
Please, revert changes to `run-cityGen2D.sh`. It is not working under linux.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

We have new changes pushed to the repository:
1º.- The vampire objects now are moving around its region looply
2º.- The vampire rotates depending on the director vector with its next path point.
3º.- The algorithm that creates the vampires path is RMDFractal based (recursive).

In order to be clearer, I'll add some screenshots that ilustrates the path of a vampire, representing the path points as white ico-spheres. that way, is easier to understand the course keeped by the vampire.

![ballpath](https://user-images.githubusercontent.com/22729865/47382953-d6000780-d703-11e8-96a2-bfc2f68f7bbc.png)
![ballpath2](https://user-images.githubusercontent.com/22729865/47382964-de584280-d703-11e8-9e7b-0cc2c3cbac99.png)

Kind regards.

**Comment by jmespadero** [comment]
I have a small proposal to optimice the run-time.

Instead of computing the angle inside of `SetVampirePosition(cont):` on every animation step,
precompute the angle and save into an array of orientations for each vampire, so the 
`SetVampirePosition(cont)` method is basically like:
```python
            own.position = path[own['vamp_index']]
            own.localOrientation = orientation[own['vamp_index']]
```

**Comment by jmespadero** [comment]
Is it my impression, or the bat is flying backwards in some streets?

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've pushed new content to the repository, as you can see. The main changes was that I have fixed the vampire rotation issue. What's more, I'm computing now each rotation angle which will be applied to the vampire in each path point only once, appending them into a list of rotations. It means that now the rotations of the vampire will be computed only one time before the execution, giving more efficiency to the application at runtime.

What's more, I have made some minor changes, like renaming some variables and adding some documentation to the code.

Next step will be to add a vampire in each region, not only one in the whole map.

Kind regards.

**Comment by jmespadero** [comment]
You rcommit b6ad582 is quite similar to expected behaviour. Do not change any more excect cosmetic changes in code.
