### ISSUE TITLE
Create Random houses

### ISSUE THREAD

**Issue by jmespadero** [jmespadero/cityGen#3]
Create pseudo-random houses starting from a basic model and placing doors, windows, etc.
Use models from Daniel74.

**Comment by jmespadero** [comment]
Just one image to explain current algorithm to build regular city regions from 2D Voronoi regions, and the _onion region model_.

cityGen3D read a set of regions that are convex polygons generated by cityGen2D. 
Each region is defined just by a list of coordinates of points in its boundary, always listed in positive orientation (that means, counter-clockwise). That boundary is the red line in this diagram, which we will call "layer0" or "external layer".

![onionregionmodel svg](https://user-images.githubusercontent.com/6451497/38827468-4dfc1422-41b3-11e8-9c3b-7e6b121425d4.png)

After loading it. cityGen3D computes the centroid of the region and create an internal layer (the green line) by scaling the layer0 to build the layer1.

The space between layer 0 and layer 1 will be the "roadway" part of the streets, usually rendered with  Floor1 material. 

The layer1 boundary is usually filled with "Curbs" objects, so we sometimes call it the "Curb layer".
The inside of layer 1 is filled with "Floor2" ground material, and will be the "sidewalk" part of the street.

The layer1 is scaled again to build an even internal layer2 (the blue line). This line/region is not rendered, but currently it is being used as a baseline to the house placement algorithm. This mean that houses have their external wall aligned with that line.

To better understanding, this is a composed image of the onion-model with a current render of the city.
![onionregionmodel2 svg](https://user-images.githubusercontent.com/6451497/38828042-11a8e6ce-41b5-11e8-9560-e3b119c5c7df.png)

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

As we decided, and following the schema you have explained last post, I've created a basic mesh per region for the houses. As I have the base-line of the "houses layer" (the blue line in the previous schema), I created a "roof-line" copy modifying the Z axis, so now I have another skeleton above the first. I have painted both with curbs for you to can see the results:

![step6_1](https://user-images.githubusercontent.com/22729865/38884239-4daf1692-426f-11e8-8360-ee915d493797.png)

When I had those two skeletons, I had append them orderedly in a new list for pass it to the from_pydata function to create the mesh. I only needed a faces list, so I created it (with quads, not with triangles) iterating over the new points ordered list and selecting the correct 4 points in the correct order.

When I had the faces list, the from_pydata function was responsible of mesh creation. I only had needed to pass it a material and the mesh name. In the next screen capture, I have deleted the boundaries painted with curbs and painted the new mesh for each region:

![step6_2](https://user-images.githubusercontent.com/22729865/38884489-150d3ae8-4270-11e8-8b16-99e9a4702c65.png)

Now, I'll divide the mesh for have different heights in the same mesh, and different materials.
Greetings!

**Comment by jmespadero** [comment]
Ok,
Now, I have a lot of medieval assets (doors, windows, stairs, etc) created by [Daniel Andersson](http://www.blendswap.com/user/Daniel74) and published with a free license in http://www.blendswap.com.

Here is a preview of the assets...
![preview_74694](https://user-images.githubusercontent.com/6451497/38917143-1d7c27dc-42ea-11e8-8e32-0ca2d394f2d5.jpg) ![preview_74695](https://user-images.githubusercontent.com/6451497/38917144-1d936974-42ea-11e8-93f0-973de47aa6c8.jpg) ![preview_74698](https://user-images.githubusercontent.com/6451497/38917145-1dab0d22-42ea-11e8-9f24-68ce3f6b1d19.jpg)
![preview_74699](https://user-images.githubusercontent.com/6451497/38917146-1dc4995e-42ea-11e8-8a52-292aad2688e3.jpg) ![preview_74700](https://user-images.githubusercontent.com/6451497/38917147-1dde0d4e-42ea-11e8-811b-fde51cb01bba.jpg) ![preview_74702](https://user-images.githubusercontent.com/6451497/38917148-1e123a4c-42ea-11e8-84e5-1f8e13c3aa71.jpg)

The main idea is to import all of them in secondary layers, the same way than cg-library.blend is imported now. Probably we could merge all of then in a new layer of cg-library.blend at the end of this issue, but don't do it for now.

Then, use your recently created mesh as a **canvas** to place the assets and build houses similar to the "house1", "house2", etc... models also created by Daniel.

**Comment by jmespadero** [comment]
Hi @sergiofv93 
I have added all the files with assets and house examples to my repo.. 
If you run the command
```
git pull upstream master
```

You should get then directly in your repository. Keep them as separate files by now, because probably we will do small modifications to them. They are binary, so it is worse to use a big file if we are changing it.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've been working with some windows and doors for paste them in the new wall mesh, but I have some questions:
- What do you mean with using the mesh as a canvas? I'm using functions like the used in the big building issue.
- I can create new windows along the wall now, but I need to give them someking of angle to adjust them to the wall direction. How can I do that with bpy?
- I'm using for now the layer 0, duplicating the objects. Now I want to import the library in the layer 2, and copy the objects in layer 0 to use them here. I'm searching for doing it with bpy, but any idea?

Thanks in advance,
greetings.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've sliced the regions in several fragments, which will be the houses, like you can see in the screen capture:

![step7_1](https://user-images.githubusercontent.com/22729865/39191177-aa869536-47d6-11e8-9441-ec2f0107316b.png)

What's more, I've pushed new content in the repository for you to be able to probe the functionality.

I've been trying to give a heigh to the houses, but I've a problem: each "quad" have 4 vertex. If I want to add more heigh to the house, I need to modify Z axis on each pair of "upper" points, but each vertex is property of 2 different houses, the left and the right, and those could be of different heighs. I don't see a solution for now, can I manipulate a point that will have "2 heighs"? One for the left house and one for the right house?

Now, I'll create new windows and doors in each house, without roof for now.

Greetings.

**Comment by jmespadero** [comment]
Nice!

For the "different height problem" you need to change your schema

Instead of your current schema:
```
A street is one mesh, consisting in a list of quads, one quad per each house.
```

Try to do:
```
A street is a list of meshes, one mesh of one quad per each house.
```

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've changed the schema as you said, and now I have a "one mesh per house" schema, as you can see in the next screen capture:

![captura de pantalla de 2018-04-25 00-01-45](https://user-images.githubusercontent.com/22729865/39216421-de3aefea-481b-11e8-9220-8ac39f28f7e1.png)

I'll keep creating doors and windows.
Greetings

**Comment by jmespadero** [comment]
Nice.

I feel that the partition created houses too narrow. Please, tune your algorithm to create wider houses.

Also, force the last house of each street have the same height than the first house in the next street, or you will have problems with the roofs in the corners. The best way is just add a "post process" step to overwrite the height of the last house with the height oh the house around the corner.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've changed the heigh in the corners of the region. Now, te houses in the corners have the same heigh, as you said, to avoid roof creation problems. What's more, I've modified the algorithm to create wider houses, as you suggested. We can see the results in the next screen capture:

![captura de pantalla de 2018-04-25 13-41-33](https://user-images.githubusercontent.com/22729865/39243687-a6ed94c0-488e-11e8-85d7-759825ba3ba3.png)

Greetings!

**Comment by jmespadero** [comment]
That was solved in the duplicateAlongSegment method:

```
        angle = (Vector((1, 0, 0))).angle(b - a)
        if (b-a).y > 0:
            angle = -angle
```
![screenshot at 2018-04-26 17-33-40](https://user-images.githubusercontent.com/6451497/39315949-354e98b0-4978-11e8-8535-1ca3dd9e5a64.png)

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

As we talked in the last meeting, I'm refactoring the algorithm for house items creation. Now I have created an extension for the 'city.data.json'. This extension is a list called 'house_templates' that contains all the house templates I'll use for creating the house assets.

The objective is to 'load' each house from a file, I mean, a file which will contains the house assets like ["ObjectName", x%, y%], where those percentages are the position of the asset between the points A and B (the house vertex).

So I'll divide the file in three blocks: houses with length smaller than 10, between 10 and 15, and bigger than 15. In each case, I've created about 5 templates, and I'll choose randomly (with random.choice method) which template will be apply to the specific house:

![captura de pantalla de 2018-05-08 12-57-54](https://user-images.githubusercontent.com/22729865/39753527-71fff6dc-52bf-11e8-9315-5a017865de2a.png)

Now, I'll implement the code for the auxiliar method "createAsset" that implements the specific conditions to each asset of the house.

Thanks and greetings.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've implemented the algorithm to create house assets reading them from a file, and I'm glad of the results, as you can see in the next screen capture. Finally, I'll adjust the position of some windows, because I think could be better:

![captura de pantalla de 2018-05-08 14-24-20](https://user-images.githubusercontent.com/22729865/39757069-fa05e0a8-52cb-11e8-95d8-8ce004058583.png)

And I have a little issue. The balcony. Some times, the house is heigher than the balcony, and it looks like this:

![captura de pantalla de 2018-05-08 14-24-43](https://user-images.githubusercontent.com/22729865/39757113-26bdf518-52cc-11e8-9346-aba78182270d.png)

I've ideas to solve it, but any suggestion will be helpful.

Greetings.

**Comment by jmespadero** [comment]
Two comments here:

1. The current commit  0d56291 is broken. You can not manually add data to `city.data.json`. That file is generated by cityGen2D.py, and overwritten every time you run it. 

2. For the balcony problem. One good solution is to store in each template values for minimum and maximum width and height of the rectangle, to decide if that template can be applied to one given rectangle. For example:
* If you have a very simple template with only a door and a window, you probably don't want to apply it to a very wide house, because the effect is that it have "too few windows for such a wide wall"
* If you have a very complex template with 3 balconies, you don't want to apply to a narrow house, because there will be no space for those elements.

So, when you create a template, you can store the dimension of the minimum and maximum valid rectangle. A proposal is:
* Precompute the sum of the widths of the windows/balconies on the most complex floor of your template. The minimum width should be that number multiplied by 1.20, for space between the windows. The maximum width would be that number multiplied by 1.8, to avoid to separate the windows too much.
* Compute the sum of heights of the maximal element in each floor. Apply the same idea, but add extra conditions for balconies: A balcony measures 2.6m in height (Z axis), so if there is a balcony at homogeneous coordinate 0.66 that mean that the balcony has to fit in the space 0.66-1.0. That mean your minimal rectangle height has to be 3 * 2.6m = 7.8m.
 

So, using your last image as example... (and knowing that a balcony measures 3.46m x 2.6m)
* For the first house: the most complex floor is the upper (a balcony). I would store minimum width = 3.46m * 1.2 = 4.15m; maximum width = 3.46m * 1.8 = 6.3m ; minimal height = 3 * 2.6m = 7.8m; maximal height = 11.7m 
* For the second house,  the most complex floor is the upper, with 2 big windows + 1 small window = 1m + 1m + 55cm = 2.55m. I would store minimum width = 2.55m * 1.2 = 3.06m; maximum width = 2.55m * 1.8 = 4.6m ; minimum height = 2 * 2.34m = 4.68m; maximum height =  7.02m
* For the third house, the minimum height should be 2 * 2.6m = 5.2m. The maximum height should be 1.5 * 5.2m = 7.8m. Meaning you probably should not have applied that template to that rectangle.

**Comment by jmespadero** [comment]
Some ideas for the roofs....

Start by editing the `cg-house-assets/cg-libExtraRoofs.blend`file to adapt to our
default graphic configuration
1. Change renderer from "Blender Render" to "Blender Game"
2. Change shading from "Multitexture" to "GLSL"
3. Change "RoofTiles" and "Wood" texture mapping from "UV" to "Global"
4. Remove Roof1Poles and Roof2Poles.
5. Join "Roof1Outer", "Roof1Frame" and "Roof1Inner" on one object (Ctrl+J). Rename as "Roof1"

**Save your file...**

6. Choose a point of view where you see the Roof1 object nicely.
7. Open a python console in blender
8. Run the commands one-by-one...
* `bpy.data.objects['Roof1'].dimensions[0] = 5`
* `bpy.data.objects['Roof1'].dimensions[0] = 2.83`
* `bpy.data.objects['Roof1'].dimensions[0] = 7`
* `bpy.data.objects['Roof1'].dimensions[2] = 2`
* `bpy.data.objects['Roof1'].dimensions[2] = 4`

If everything is correct, you should see how Roof1 adapts to your sizes. You can freely change the
width and height of the Roof1, and it should scale nicely (the texture does not create tiny or huge elements)
![screenshot at 2018-05-08 20-02-08](https://user-images.githubusercontent.com/6451497/39774429-1be0c588-52fb-11e8-80e4-dc017ee63fc3.png)

So this give you a method to create roofs of any size. You should adapt the width to the width of your house, and select a random height to make roof seem different.

The same procedure can be applied to "Roof2"

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've finished the algorithm for house assets creation. I've created new house templates, and now we have 13, divide in three blocks: narrower than length 10, between 10 and 15, and wider than 15. And, in each block, we have other three sub-blocks for the heigh (smaller than 8, between 8 and 10, and bigger than 10). Now I can "control" the templates that will be apply to a house depending on its width and heigh.
Therefore, the balconies will no longer be out of place.

I'm very happy with the new results:

![captura de pantalla de 2018-05-09 17-23-07](https://user-images.githubusercontent.com/22729865/39823971-81877702-53ae-11e8-916a-5e4554500144.png)

Please, give me any final suggestions you have, and I'll keep working with the roofs.

Greetings.

**Comment by jmespadero** [comment]
There is a problem in your image. A door is breaking the roof of the balcony. 
It would create a new kind of door, without the stone step an smaller than the doors used for street.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've fixed the issue that you commented in the last message. I have added a scale factor to the template tuple that controls the scale of an object What's more, I've rised up the doors located in a balcony 0.01 meters. That way, I don't have to create a third door without stone step, we won't see it while we are playing the game, and with the scale factor, I have managed to ensure the balcony door fits properly to the balcony:

![captura de pantalla de 2018-05-10 16-25-34](https://user-images.githubusercontent.com/22729865/39874755-06c91464-546f-11e8-98b5-8074a268d8f6.png)
![captura de pantalla de 2018-05-10 16-27-09](https://user-images.githubusercontent.com/22729865/39874757-06f9dad6-546f-11e8-9a71-623ea64f69d9.png)


Thanks in advance,
greetings.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I'm working with the roofs now, and I have several questions:

1º.- If I create the roofs as you said, I point that the triangle between the house upper points and the medium point of the roof keeps empty. We will have to fill it with an additional house wall fragment?

2º.- When I'll have the roofs created, I could see a bug: the bigger houses haven't lateral walls, so we will see the roofs over a lone wall... fisically impossible. I'll must create lateral walls between houses to solve it?

Thanks in advance,
greetings.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

the roof results for now:

![captura de pantalla de 2018-05-10 18-24-23](https://user-images.githubusercontent.com/22729865/39880922-7336977e-547f-11e8-879f-1b2f61e81ee9.png)

![captura de pantalla de 2018-05-10 18-25-55](https://user-images.githubusercontent.com/22729865/39880973-a1a7f85a-547f-11e8-9cb1-ef9cc67235b3.png)

It was very simple to create the roofs. I've only have to determine the origin of the roof object, than compute the medium point between the upper points of the house, the length between them, and simply create the roof in that point with that length in the X dimension, rotate it, and finished.

Greetings

**Comment by jmespadero** [comment]
Here is a pair of URL with examples of creating a mesh with UV coordinates

1. https://blenderartists.org/t/creating-a-uv-map-using-python/671835
2. https://blender.stackexchange.com/questions/711/how-to-add-a-uv-map-to-a-mesh-using-python

**Comment by jmespadero** [comment]
> From email:
> ¿como puedo calcular un vector "v1" partiendo de otro vector "v2" y sabiendo el ángulo "angle" que tienen que formar entre ellos?

You can rotate a vector with the rotate() method, which accepts an [Euler](https://docs.blender.org/api/current/mathutils.html#mathutils.Euler), [Quaternion](https://docs.blender.org/api/current/mathutils.html#mathutils.Quaternion), or a Matrix. 

Knowing that you want to rotate always around Z-axis, I would use [Euler](https://docs.blender.org/api/current/mathutils.html#mathutils.Euler).
```
myVec =Vector((1,0,0))
myVec.rotate(Euler((0,0,angle)))
print(myVec)
``` 
Or, as second option... you can use a [Quaternion](https://docs.blender.org/api/current/mathutils.html#mathutils.Quaternion).
```
myVec =Vector((1,0,0))
myVec.rotate(Quaternion((0.0, 0.0, 1.0), angle))
print(myVec)
```

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

Thanks for the last tips, but I've only got a trivial progress. I've been looking at https://docs.blender.org/api/2.78a/bmesh.html at "Example Script" section, and now I know how to initialize a BMesh, but I haven't very clear whatto do next.

Obviously, set the UV coordinates into the loop, but what's the entry point? I guess that the house coordinates, the two "base points" and the 3 "roof points". Is it correct?

If so, after browsing around the web, I think the correct code for set the coordinates is something like this:
```
for v in bm.verts:
    v.co.x = 1.0
```
but I'm not very sure yet. And the "CustomData Access" section of the mentioned web does not clarify the issue very well.

Thanks in advance,
greetings.

**Comment by jmespadero** [comment]
In that example, change the code...
```python
for v in bm.verts:
    v.co.x += 1.0
```
to something like this...
```python
uv_layer = bm.loops.layers.uv.verify()
bm.faces.layers.tex.verify()

for f in bm.faces:
    for l in f.loops:
        l[uv_layer].uv = <<your UV generated from a, b, h>>

```

**Comment by jmespadero** [comment]
From email:
>En el código que me pasaste en el mail tenemos 2 bucles, uno para las facetas entiendo y otro para "loops" que no se muy bien que son los loops de la malla en ese punto, cuando todavía no le han sido asignados puntos o facetas, dado que eso se hace en la llamada a la funcion from_pydata().
>
>Luego, la uv_layer tampoco tengo muy claro qué es, dado que la utilizas en el codigo que me pasaste como índice de cada loop, y la asignación que debo hacerle por tanto tampoco la entiendo, no se si tengo que asignar el punto a, b, ah y bh, o asignarle una lista con los 4 puntos de la casa, o qué hacer exactamente.
>
>Me parece que no entendí muy bien el asunto del mapeado UV, sé en que consiste y lo he visto gráficamente, pero a la hora de codigicarlo ignoraba que hubiera que trabajar con layers, facetas de maya y loops.

From [bmesh documentation](https://docs.blender.org/api/2.78a/bmesh.types.html#bmesh.types.BMLoop):
```
each face loop represents a corner of the face.
```

why assign UV to corners instead of vertex? Because sometimes you want that a vertex has a different  UV coordinate depending of each face. For example... in the seams of this sphere
![image](https://user-images.githubusercontent.com/6451497/40380974-c9ba1c4a-5dfa-11e8-8e1a-57a30d337bce.png)


But you really don't need to worry about that... you just need to build the U and V coordinates for each loop (=corner). If you have assigned the xyz coordinates to the vertex, you can build  UV from these.

The easy is V, because is just he Z coordinate (maybe, multiplied by a factor)
The U coordinate is the distance from the point to the origin vertex of your house. The easy way is just to compute the distance in XY and ignore Z (which you call the "a" point).

```python
uv_layer = bm.loops.layers.uv.verify()
bm.faces.layers.tex.verify()
for f in bm.faces:
    for l in f.loops:
        #print xyz coordinates of this loop
        print("xyz:", l.vert.co)
        l[uv_layer].u = <<distance from l.vert.co.xy to a.xy>>
        l[uv_layer].v = l.vert.co.z
        print("uv:", l[uv_layer].uv)
```

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

thanks for the tips, at least I've continued with the progress. Now the material of the houses fits well. Thanks for your explanation.

Greetings.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've pushed new content to the repository with the RoofBars code, but it has a problem. The objects XY plane orientation is the angle between the object and the X axis, so the objects XZ plane orientation should be the angle between the object and the Z axis. Then, I'll have to asign the angle to the Y rotation, but the obtained results are not as expected:

![captura de pantalla de 2018-06-06 12-29-58](https://user-images.githubusercontent.com/22729865/41035180-2289cbbc-698c-11e8-909a-760ef7d48371.png)

The code that controls this functionality is in the CityGen3D.py, line 427. What could be the problem?

Greetings.

**Comment by jmespadero** [comment]
Can't see that code. Your last push was 2 days ago...

**Comment by sergiofv93** [comment]
There was a git connection failure. Already pushed.

**Comment by jmespadero** [comment]
I have added this after line 427
```python
        print(roofbar.name, roofbar.rotation_euler )
```

And I get this...
```
RoofBar.001 <Euler (x=0.0000, y=1.5708, z=2.8098), order='XYZ'>
RoofBar.002 <Euler (x=0.0000, y=1.5708, z=2.8098), order='XYZ'>
RoofBar.003 <Euler (x=0.0000, y=1.5708, z=2.7157), order='XYZ'>
RoofBar.004 <Euler (x=0.0000, y=1.5708, z=2.7157), order='XYZ'>
RoofBar.005 <Euler (x=0.0000, y=-1.5708, z=-1.4793), order='XYZ'>
RoofBar.006 <Euler (x=0.0000, y=-1.5708, z=-1.4793), order='XYZ'>
RoofBar.007 <Euler (x=0.0000, y=-1.5708, z=-1.4764), order='XYZ'>
```

Every euler.y value is -1.5708 radians (that is -90 degrees), which comes from `getAngle(points[3], points[1], Vector((0, 0, 1)))`

It is ok to repeat the use of points[3], points[1] on every loop?
What does it mean and points[3], points[1] ? Can you plot a figure?

**Comment by jmespadero** [comment]
Another idea...
Knowing that your original RoofBar is aligned with Vector(1,0,0) why don't you try directly
https://docs.blender.org/api/blender_python_api_current/mathutils.html?highlight=rotation_difference#mathutils.Vector.rotation_difference

and do 
```
roofbar.rotation = Vector((1,0,0)).rotation_difference(end_point - ini_point)

```

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

sorry, you are right, is better to see it in a figure:
![captura de pantalla de 2018-06-06 18-01-25](https://user-images.githubusercontent.com/22729865/41051344-26a07258-69b6-11e8-8798-cb15af7b2714.png)

As you can see, half of houses have the correct roof bar, but the others (angle negative) have not the bars with the correct rotation. I've plot the vertex and the vectors V1 and V2.

v1 = Vector((0, 0, 1)), v2 = Vector ((1, 0, 0))

The problem is that I'm making a mistake computing the point3 - point2 and point2 - point1 angles with v1. I think that the problem is the method 'getAngle' at line 390. We had that when the y was smaller than 0, the angle will be negative... but I think that in this issue, the clue is not the y coordinate of the angle.

Can u see the mistake?

Greetings

**Comment by jmespadero** [comment]
I think is because of [this function](https://github.com/sergiofv93/cityGen/blob/4de47c107b74189345627e04419cd2fc6fef6877/cityGen3D.py#L390)...

```python
def getAngle(a, b, v = Vector((1,0,0))):
    angle = v.angle(b - a)
    if ((b - a).y < 0):
        angle = -angle

return angle
```

At line 392, you are examining the sign of `(b - a).y` which is OK for 2D but not for arbitrary 3D. That function is always examining the Y coordinate

**Comment by jmespadero** [comment]
So the "old-school" solution is to compute a 3D Rotation (not an angle)...

Your original roofBar object is aligned with X-axis, so you want to compute a rotation that convert `Vector((1,0,0))` to your roofBar direction. To build the rotation, you use an axis which is perpendicular to both, which you can compute as a cross product, and an angle, which you can compute with the dot product.

```python
        rootbar_direction = (points[i+1]-points[i]).normalized()
        axis = Vector((1,0,0)).cross(rootbar_direction)
        rotation = Quaternion(axis, acos(rootbar_direction.x))
        roofbar.rotation_euler = rotation.to_euler() 
```
![screenshot at 2018-06-07 15-33-33](https://user-images.githubusercontent.com/6451497/41103023-73759254-6a68-11e8-9af9-bce7304cf65e.png)

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

I've progressed in the creation of roofs at the vertices of each region. The refactorization of all the code that implements the functionality of house creation, the creation of flags to know if a house is part of a corner or not is too complex, so I had an idea to make the roof fit well to the corners.

I'd not deleted the lateral walls for the corner houses. They didn't disturb me because they will be behind the house mesh and the two corner houses for each corner region have the same heigh, so I only have to adjust the roof without deleting lateral walls.

The results are like this:
![captura de pantalla de 2018-06-11 16-13-01](https://user-images.githubusercontent.com/22729865/41236893-82c217be-6d92-11e8-88bd-6b685c5a3dc3.png)
![captura de pantalla de 2018-06-11 16-14-10](https://user-images.githubusercontent.com/22729865/41236894-82debe78-6d92-11e8-9de8-a9d1957acb1f.png)

It could seems like a bad solution, but when the user is playing, he can't see the empty space between the roofs. Hope this solution will be enough to consider finished the issue.

Greetings.

**Comment by jmespadero** [comment]
Could you please push that code? Currently your randomHouses branch is broken...

**Comment by sergiofv93** [comment]
I've pushed the code, but I get this error:


![captura de pantalla de 2018-06-11 17-42-05](https://user-images.githubusercontent.com/22729865/41242223-38940960-6d9f-11e8-92fe-eba5ff8d64f8.png)

I think I broke the branch or similar when I did checkout to previous commit. How can I fix it?

Greetings.

**Comment by sergiofv93** [comment]
I think I get this message because I did checkout to a commit, not to a branch. So I'm leaving 2 commits behind, not connected to any of my branches.

I'm looking for a solution on Internet, but I'm scared to lose my changes if I do something wrong. I've seen that te solution could be to execute the commands:
`git reflog`
`git checkout -b temp HEAD@{3}`

is it correct?

Greetings

**Comment by jmespadero** [comment]
Not sure...

But I would do this: Just copy your source files to a temp directory. Then do `git checkout .` to attach again to HEAD,  and then copy the files back from your temp directory to your source directory.
Then you can do your tipical  "git add" and "git commit"

**Comment by sergiofv93** [comment]
I'm trying it, but I have another unknown error that I can't solve:

![captura de pantalla de 2018-06-12 18-02-35](https://user-images.githubusercontent.com/22729865/41302531-fb611b74-6e6a-11e8-8197-ad40541f9ddf.png)

I have the new code in the cityGen3D.py file, but I don't want to push it with this error.

**Comment by sergiofv93** [comment]
Hi @jmespadero ,

as we talk in the last meeting, I have pushed thenew content to the repository, and I think it would be enough to close this issue. Finally, the changes were:
 - Creation of base points for houses
 - Creation of a mesh (BMesh) for each house
 - Distribution of house assets, like windows, doors or balconies
 - Addition of textures to the house meshes
 - Creation of roofs for the houses (with bug in corners)
 - Creation and distribution of wooden beams for house roofs
 - Refactorization of the roof creation algorithm (corners bug solved)

I will do a pull request right now, thanks for your help in this issue.

Greetings.

**Comment by jmespadero** [comment]
Right. Im gonna close this issue.
